# Generated by Django 5.2.7 on 2025-10-11 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Context')),
                ('text_date', models.DateField(blank=True, null=True, verbose_name='Context date')),
                ('source', models.CharField(max_length=255, verbose_name='Context source')),
            ],
            options={
                'verbose_name': 'Context',
                'verbose_name_plural': 'Contexts',
                'ordering': ['text_date'],
            },
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Definition')),
            ],
            options={
                'verbose_name': 'Definition',
                'verbose_name_plural': 'Definitions',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='GeneralChar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='General characteristic')),
            ],
            options={
                'verbose_name': 'General Characteristic',
                'verbose_name_plural': 'General Characteristics',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='GrammClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Grammatical class')),
            ],
            options={
                'verbose_name': 'Grammatical Class',
                'verbose_name_plural': 'Grammatical Classes',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='SpecificChar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Specific characteristic')),
            ],
            options={
                'verbose_name': 'Specific Characteristic',
                'verbose_name_plural': 'Specific Characteristics',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='TradRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Traditional relation')),
            ],
            options={
                'verbose_name': 'Traditional Relation',
                'verbose_name_plural': 'Traditional Relations',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='TradTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Traditional term')),
                ('definition', models.TextField(verbose_name='Traditional term definition')),
            ],
            options={
                'verbose_name': 'Traditional Term',
                'verbose_name_plural': 'Traditional Terms',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_anl', models.TextField(verbose_name='Conceptual analysis')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='voc.context', verbose_name='Context')),
                ('term_def', models.ManyToManyField(related_name='entries', to='voc.definition', verbose_name='Term definition')),
                ('general_char', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='voc.generalchar', verbose_name='General Characteristic')),
                ('term_gramm_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='voc.grammclass', verbose_name='Term grammatical class')),
                ('specific_char', models.ManyToManyField(related_name='entries', to='voc.specificchar', verbose_name='Specific characteristic')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Term')),
                ('contexts', models.ManyToManyField(related_name='terms', through='voc.Entry', to='voc.context', verbose_name='Contexts')),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
                'ordering': ['text'],
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='voc.term', verbose_name='Term'),
        ),
        migrations.AddField(
            model_name='entry',
            name='trad_relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='voc.tradrelation', verbose_name='Traditional relation'),
        ),
        migrations.AddField(
            model_name='entry',
            name='trad_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='voc.tradterm', verbose_name='Traditional term'),
        ),
    ]
