# Generated by Django 5.2.7 on 2025-10-31 20:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('full_name', models.CharField(blank=True, help_text='Used when author name does not fit standard first/last pattern (e.g. Michel de Montaigne).', max_length=255, verbose_name='Full name')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Cotext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Cotext')),
                ('text_date', models.DateField(blank=True, null=True, verbose_name='Cotext date')),
                ('loc_in_ref', models.CharField(blank=True, help_text='e.g. p. 84.', max_length=100, null=True, verbose_name='Location in reference')),
            ],
            options={
                'verbose_name': 'Cotext',
                'verbose_name_plural': 'Cotexts',
            },
        ),
        migrations.RemoveField(
            model_name='term',
            name='contexts',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='context',
        ),
        migrations.AlterModelOptions(
            name='definition',
            options={'verbose_name': 'Definition', 'verbose_name_plural': 'Definitions'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='tradrelation',
            options={'ordering': ['text'], 'verbose_name': 'Relation Between Term and Traditional Term', 'verbose_name_plural': 'Relations Between Term and Traditional Term'},
        ),
        migrations.AddField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='general_char',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='voc.generalchar', verbose_name='General characteristic'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='trad_relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='voc.tradrelation', verbose_name='Relation Term and Trad. Term'),
        ),
        migrations.AlterField(
            model_name='tradrelation',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Relation'),
        ),
        migrations.AddField(
            model_name='entry',
            name='cotext',
            field=models.ManyToManyField(related_name='entries', to='voc.cotext', verbose_name='Cotext'),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Publication year')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Publisher')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Publication city')),
                ('source_type', models.CharField(choices=[('BOOK', 'Book'), ('ARTICLE', 'Article'), ('CHAPTER', 'Book Chapter'), ('THESIS', 'Thesis'), ('ONLINE', 'Online Resource'), ('OTHER', 'Other')], default='BOOK', max_length=50, verbose_name='Source type')),
                ('citation', models.TextField(blank=True, help_text='Optional preformatted citation text (e.g. APA or ABNT style).', verbose_name='Formatted citation')),
                ('authors', models.ManyToManyField(blank=True, related_name='references', to='voc.author')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='cotext',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotexts', to='voc.reference'),
        ),
        migrations.DeleteModel(
            name='Context',
        ),
    ]
