# Generated by Django 5.2.7 on 2025-11-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc', '0002_author_cotext_remove_term_contexts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='homonym_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='Used to distinguish homonymous entries of the same term (e.g., ¹, ², ³).', verbose_name='Homonym number'),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('term', 'homonym_number')},
        ),
    ]
