# Generated by Django 5.2.7 on 2025-11-07 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc', '0003_entry_homonym_number_alter_entry_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotext',
            name='date_granularity',
            field=models.SmallIntegerField(choices=[(0, 'No date'), (1, 'Year'), (2, 'Year and month'), (3, 'Full date')], default=3, verbose_name='Cotext date granularity'),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='cotext',
        ),
        migrations.CreateModel(
            name='EntryRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SYNONYM', 'Synonym'), ('ANTONYM', 'Antonym')], max_length=50, verbose_name='Relation type')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_source', to='voc.entry', verbose_name='Entry')),
                ('related_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_target', to='voc.entry', verbose_name='Related Entry')),
            ],
            options={
                'verbose_name': 'Entry Relations',
                'verbose_name_plural': 'Entry Relations',
                'ordering': ['entry', 'type', 'related_entry'],
                'unique_together': {('entry', 'type', 'related_entry')},
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='related_entries',
            field=models.ManyToManyField(blank=True, through='voc.EntryRelations', through_fields=('entry', 'related_entry'), to='voc.entry', verbose_name='Related entries'),
        ),
        migrations.AddField(
            model_name='entry',
            name='cotext',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='voc.cotext', verbose_name='Cotext'),
        ),
    ]
