# Generated by Django 5.2.7 on 2025-11-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc', '0004_cotext_date_granularity_remove_entry_cotext_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['id'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AddField(
            model_name='term',
            name='phonetic_transcription',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phonetic transcription'),
        ),
    ]
