# Generated by Django 5.2.7 on 2025-11-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc', '0005_alter_entry_options_term_phonetic_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from term text and homonym number.', max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
