# Generated by Django 5.2.7 on 2025-11-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc', '0006_entry_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from name.', max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
