# Generated by Django 5.2.7 on 2025-11-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc', '0008_tradterm_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from name if not provided.', max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from term text and homonym number if not provided.', max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tradterm',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from text if not provided.', max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
