# Generated by Django 5.2.7 on 2025-11-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc', '0009_alter_author_slug_alter_entry_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='related_entries',
            field=models.ManyToManyField(blank=True, through='voc.EntryRelations', to='voc.entry', verbose_name='Related entries'),
        ),
    ]
