# Generated by Django 5.2.7 on 2025-12-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc', '0011_author_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryrelations',
            name='type',
            field=models.CharField(choices=[('SYNONYM', 'Synonym'), ('ANTONYM', 'Antonym'), ('NEAR-SYNONYM', 'Near-synonym')], max_length=50, verbose_name='Relation type'),
        ),
    ]
