# Generated by Django 5.2.7 on 2025-12-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc', '0012_alter_entryrelations_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotext',
            name='loc_in_ref',
            field=models.CharField(blank=True, help_text='e.g. "p. 84"', max_length=100, null=True, verbose_name='Location in reference'),
        ),
        migrations.AlterField(
            model_name='cotext',
            name='text',
            field=models.TextField(help_text='The text should be enclosed in quotation marks ("").', verbose_name='Cotext'),
        ),
    ]
