# Generated by Django 5.2.7 on 2026-05-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voc', '0013_alter_cotext_loc_in_ref_alter_cotext_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name'], 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
    ]
